CC = gcc
CFLAGS = -Wall -Werror -Wextra

.PHONY: state_sort state_search clear_state

state_sort:
	$(CC) $(CFLAGS) state_sort.c -o ../build/Quest_1

state_search:
	$(CC) $(CFLAGS) state_search.c -o ../build/Quest_2

clear_state:
	$(CC) $(CFLAGS) clear_state.c -o ../build/Quest_3
